// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

const int EV_MASK_OK_BUTTON = 1;

const int EV_MASK_PREVIOUS_BUTTON = 2;

const int EV_MASK_NEXT_BUTTON = 4;

const int EV_MASK_UP_BUTTON = 8;

const int EV_MASK_DOWN_BUTTON = 16;

const int EV_MASK_HOME_BUTTON = 32;

const int EV_MASK_SELECT_BUTTON = 64;

const int EV_MASK_START_BUTTON = 128;

const int EV_MASK_STOP_BUTTON = 256;

const int EV_MASK_PAUSE_BUTTON = 512;

const int EV_MASK_END_OF_AUDIO = 1024;

const int EV_MASK_ALL = 4294967295;
