name: BuildStoryEditor-Windows

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build_win:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: install_deps
          run : |
               choco install wget -y
               choco install nsis -y
               choco install ninja -y
        - name: build
          working-directory: ./story-editor
          run : |
              mkdir build
              cd build
              cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
              ninja
              ls
              mkdir story-editor
              cp story-editor.exe story-editor
        - name: package_setup
          working-directory: ./story-editor
          run : |
              makensis.exe /V3 nsis-installer.nsi
        - name: upload_zip_artefact
          uses: actions/upload-artifact@v3
          with:
            name: StoryEditorWindows-Zip
            path: ./story-editor/build/story-editor
        - name: upload_stup_artefact
          uses: actions/upload-artifact@v3
          with:
            name: StoryEditorWindows-Setup
            path: ./story-editor/build/story-editor-setup.exe
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
                ./story-editor/build/story-editor-setup.exe
                ./story-editor/build/StoryEditor-Windows.zip
