name: BuildAndPackage

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
env:
  QT_VERSION: 6.5.1

jobs:
  build_linux:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: install_deps
          run : |
            pip install aqtinstall
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install build-essential cmake libgl1-mesa-dev libpulse-dev
            sudo apt-get install libxcb-*
            sudo apt-get install libxkb-*
            sudo apt-get install libcln-dev libqalculate-dev
            sudo apt-get install libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
        - name: install_qt
          run : |
               python3 -m aqt install-qt -m qtwebengine -O ${{ github.workspace }}/Qt/ linux desktop ${{ env.QT_VERSION }}
               echo ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/gcc_64/bin/ >> $GITHUB_PATH
        - name: build
          run: |
              mkdir build && cd build
              cmake ../story-editor CMAKE_BUILD_TYPE+=Release
              make
        - name: appimage
          run: |
              wget -O deploy.AppImage https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
              chmod +x deploy.AppImage
              mkdir appdir
              cp story-editor appdir/
              export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/gcc_64/lib/
              ./deploy.AppImage appdir/story-editor -no-translations -bundle-non-qt-libs -extra-plugins=platforms/,sqldrivers/
              mkdir -p appdir/usr/share/open-story-teller/
              cp *.qm appdir/usr/share/open-story-teller
              wget -O tool.AppImage https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
              chmod +x tool.AppImage
              ./tool.AppImage appdir/
        - name: upload_artefact
          uses: actions/upload-artifact@v2
          with:
            name: OpenJournalLinux
            path: ./build/StoryEditorl-x86_64.AppImage
  
