name: BuildAndPackage

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
env:
  QT_VERSION: 6.5.1

jobs:
  build_linux:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: install_deps
          run : |
            pip install aqtinstall
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install build-essential cmake libgl1-mesa-dev libpulse-dev
            sudo apt-get install libxcb-*
            sudo apt-get install libxkb-*
            sudo apt-get install libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
        - name: install_qt
          run : |
               python3 -m aqt install-qt -m qtmultimedia -O ${{ github.workspace }}/Qt/ linux desktop ${{ env.QT_VERSION }}
               echo ${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/gcc_64/bin/ >> $GITHUB_PATH
        - name: build
          run: |
              mkdir build && cd build
              cmake ../story-editor -DCMAKE_BUILD_TYPE=Release -DQt6_DIR=${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/gcc_64/gcc_64/lib/cmake/Qt6
              make
        - name: appimage
          run: |
              wget -O deploy.AppImage https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
              chmod +x deploy.AppImage
              mkdir -p appdir/usr/bin
              mkdir -p appdir/usr/lib
              mkdir -p appdir/usr/share/applications
              mkdir -p appdir/usr/share/icons/hicolor/512x512
              cp story-editor appdir/usr/bin
              cp ../story-editor.desktop appdir/usr/share/applications
              
              cd appdir
              ../deploy.AppImage usr/share/applications/story-editor.desktop -qmake=${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/gcc_64/bin/qmake -appimage -always-overwrite
              
        - name: upload_artefact
          uses: actions/upload-artifact@v3
          with:
            name: StoryEditorLinux
            path: ./build/StoryEditor*.AppImage
  
