name: build-story-editor

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build_linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Install packages
          run : |
              sudo apt-get update -qq
              sudo apt-get install build-essential
              sudo apt-get install cmake
              sudo apt install mesa-common-dev libgl1-mesa-dev libgles2-mesa-dev
        - name: build
          working-directory: ./story-editor
          run : |
              mkdir build
              cd build
              cmake -DCMAKE_BUILD_TYPE=Release ..
              make
              ls
        - name: package_setup
          working-directory: ./story-editor/build
          run : |
              cpack
              cpack -G DEB
              ls
  build_win32:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: build
          working-directory: ./story-editor
          run : |
              ./create_docker_image_win.sh
              ./build_win32.sh
