name: build-story-editor

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build_linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: build
          working-directory: ./story-editor/delivery
          run : |
              ./linux_01_docker_build_image.sh
              ./linux_02_docker_launch_build.sh
              ./linux_02_docker_launch_package.sh
  build_win32:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: build
          working-directory: ./story-editor/delivery
          run : |
              ./mingw64_01_docker_build_image.sh
              ./mingw64_02_docker_launch_build.sh

